---
deployment:
  tasks:
    - composer install
    - export DEPLOYPATH=/home/u1578665/public_html/
    - /bin/cp -R * $DEPLOYPATH
    # - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp -R ./public/* $DEPLOYPATH/public_html/

