---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1578665/
    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/patria-maritime-lines.website
    # - export DEPLOYPATH=/home/u1578665/
    # - composer install
    # - /bin/cp -R * $DEPLOYPATH
    # - /bin/cp -a * $DEPLOYPATH
