---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1578665/
    # - /bin/cp .env.example testedit.ph $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -a * $DEPLOYPATH
    - /bin/cp -R ./public/* $DEPLOYPATH/public_html/patria-maritime-lines.website
    # - export DEPLOYPATH=/home/u1578665/
    - composer update
