---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1578665/public_html/patria-maritime-lines.website
    # - export PUBLIC=/home/u1578665/public_html/patria-maritime-lines.website
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -a * $DEPLOYPATH
    - /bin/cp .env.example .env $DEPLOYPATH

    # - /bin/cp -R ./public/* $PUBLIC
    # - export DEPLOYPATH=/home/u1578665/
    # - composer update

    # symbolic link apps to public html
    # - /bin/ln -s /home/u1578665/home/u1578665/public_html/patria-maritime-lines.website/storage /home/u1578665/public_html/patria-maritime-lines.website/public
